language: ruby
cache: bundler
rvm:
- 2.4.0
before_script:
- ./travis.sh
script:
- bundle exec jekyll --version
- ls -lah
- JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: AKIAIH6ZAE5UVSWXTBHA
  secret_access_key:
    secure: aWwy5n7O3/cYxprcFzOYNM3tTGJIjPqIaBaA07aCrmNKqwLMi4KN7bn3UO15MLNpwv5UmOVwhA1sluQnD6pgQ0LpzUnwfa4R7XPZmGeqC7equ+xwHVb7sslPBycqwha/ji2Lg0sC7VfxgccOoM6eTYRk5JczNqyw8RWkygTzO3pAUK66uONuv7Zy687nqgB+OLpMSQfhK+x5tjueg8p7gIUlgoC0GEfMz/O0HmC7ei0KjBx2bzsdNuxpDexlMMC9M+hfz28GC8t128chQwPjYnkqP7CMmU5JmFtRhOHHlJLwg5xJwR+JKaomWPnxNMP7rFmdR9xfZXiZsKubgGeWsVGhqjETd35WFZ5sfhcm9/YRz4pFLAAoBkDKZsQjmgyTfeLrDm1IOYCNURwWx4Dg80n+Bkwvg6oLDN71O7TN/BAPtxqwmCZUy1tyVvlCBSYFv2julV+MfsQj92i3mR/p2Kebp4ysGxERwL2YPbRh9TMMOsYzPLtXtsZNE1ik2gKxXvppcpnz3SHEzHI16sh5rrwsRDig0S0/+Rc/crZEefuv+4WxUWwnJzHqqSjV+dwhiDq0lK86I+L4YaXkhNGtGvphgdavEvr8XWl8R4V+MgdRbhVASKJL/QaESA1d0N4CwE3Wux2LBoVBqgwqc27FIM55U/zAHXUBK4j7aXJkTz0=
  bucket: vvv.org
  local-dir: _site
  upload-dir: "master" #"$TRAVIS_BRANCH"
  acl: public_read
  on:
    repo: Varying-Vagrant-Vagrants/varyingvagrantvagrants.org
    branch: main
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  default_text_charset: utf-8
notifications:
  slack:
    secure: CddsoPHMBkoF6z4q4DIH78AugR86JJeLa7vQ+rad2q/QkcyhUxiufABiNwOw6Dk07w1wFelfixTJpkwbx1zU1D4VmcMShTuuRpBfiLyeDx6JW4A5fmLp1Z38rHxJLTAGMK3S3Qe7MGQcXBk9SuOT6FRuqZmbqYBbXYEGcgZ4X4dS8IRx1A5/BTFhyvdxrGU3/gEOxwCoB3YZSLqp3A6pHqFCo3Rl4xHNb/iUFOMsuf80ZZjg76DOwlXf7lqtxN9OBlYHt1MaBvAg3fQq3RoReNjDGq09MH/7rFRgnQwNBR2cKaQTtLQDFTWyvxjO9s6rrYS+8pdgnLK+aDO3t83nUdaUBEBNlCwJSS6VEzSdGkxwbcxxof0xkEmvhHnGH7Rkee3GMuOFnJ3rkWoIbGTPQCCzMkeA5ey6hcEVyG8dtIUBRQjby1Kr0lBIDOGTkk03r2+yCcErJ76Lgs60g1VxDZ89CyhGQiyZXz/ZtbNR5+BzIgdvpsVQOJ8avaIwnrggRu8rW9Z0liWNJDeaoFrZr4QBzcsW23iadUikl/SnQEgk70o1/rOIq2ZCybZRbQoz1j4EZftZ/WF4Zklz/7L0rcUd67l/u86NRufPfpwKbf/P7/xux61oanhycV0PXLHp6SWsRCco2LiKn1hL0w5Vf5KfI4dCIsZsYcUTZEKZ4tY=
