# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thunder
email: saddam.azad@me.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cloudbits.io" # the base hostname & protocol for your site
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
paginate: 10
paginate_path: /blog/page:num
exclude:
  - vendor
  - README.md
  - Gemfile*
  - LICENCE
github_repository_url: "https://github.com/cloudbitsio/cloudbits-docs"


# ----
# Site

show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/thunder.png
description: "Documentation for Thunder Back-end-as-Service with Local Development for Wordpress."

twitter:
  card: summary

# -----
# Build

#permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: /images/thunder.png
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
